### ISSUE TITLE
[Question] BottomNavigation integration

### ISSUE THREAD

**Issue by cyril-tl** [alexmamo/RoomJetpackCompose#1]
Hello, I have a question about bottom navigation.
How can I integrate such functionnality in your project ? 

I found that the Scaffold usually encapsulate the whole screen as you can see in this repo [here](https://github.com/DaaniDev/jetpack_compose_animations/blob/master/app/src/main/java/com/daanidev/compose/bottomnav/BottomNavActivity.kt)

But on the contrary you put a Scaffold for every screen page.

Do you have an idea on how I could do that ?

**Comment by AlexMamo** [comment]
As far as I know, if we have parts that look the same for all screens, then we can place the Scaffold for the whole app. If we have parts that differ, we can place the Scaffold in each individual screen. I don't see anything wrong.

**Comment by cyril-tl** [comment]
Thanks, I better understand this now, here is my solution to use a BottomBar :

```
@SuppressLint("UnusedMaterialScaffoldPaddingParameter")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            val navController = rememberNavController()
            Scaffold(
                bottomBar = { BottomNavigationBar(navController) }
            ) {
                NavGraph(navController = navController)
            }
        }
    }
```

As you can see I have to use a 

`@SuppressLint("UnusedMaterialScaffoldPaddingParameter")`

And I had to add a modifier = Modifier.padding(bottom = 50.dp), inside the Scaffold of each screen.

**Comment by AlexMamo** [comment]
That's a nice approach ;) Thanks for adding here. It may also help other future visitors.
